### ISSUE TITLE
Does not seem to work across nodes

### ISSUE THREAD

**Issue by rajbarua** [aws-samples/eks-install-guide-for-multus#7]
If I take the example configuration and force the pods to be hosted to separate nodes with `nodeSelector`, communication across the pods breaks. 
```
  nodeSelector:
    kubernetes.io/hostname: ip-10-0-2-x.ap-south-1.compute.internal
```
Is multus-cni in EKS only supposed for work on single node? I have tried `ipvlan` and `macvlan` both of which work on single node but do not work across nodes.

**Comment by boeboe** [comment]
+1

Same observation here. I have tried the following scenario's:

 - Calico + Multus
 - Aws-VPC-CNI + Multus

All works well as long as POD's are scheduled on the same node, but as soon as they are scheduled on different nodes. the traffic does not arrive at the target node.

    POD1 => Node1 ==(this is where the traffic is not arriving at node2)==> Node2 => POD2

    - Ping to node1 IP: OK
    - Ping to node2 IP: OK
    - Ping to POD2 secondary IP: NOK (ICMP requests for POD2_IP2 are never responded and also not arriving on Node2 (tcpdump verified)

I tried with `ipvlan` (l2 and l3), `macvlan` (bridge)... my guess is that the MAC addresses are not discovered/reachable on the secondary subnet. I tried to resolve this by also switching to `aws-vpc-cni` on this interfaces, but then my PODs get random primary ClusterIP addresses inside k8s (some will get primary subnet IPs, others secondary IPs).

I assume that Multus support is still under development. Where can I follow up on the progress and roadmap thereof?

I also reached out for support here:
https://github.com/k8snetworkplumbingwg/multus-cni/issues/767

The issue is also very similar to the one described here (in the end when MAC addresses are mentioned in a Virtualized Network):
https://github.com/k8snetworkplumbingwg/multus-cni/issues/390

Kind regards,
Bart

**Comment by boeboe** [comment]
**Update:**

 I found the answer I was looking for at https://github.com/aws-samples/eks-automated-ipmgmt-multus-pods

**Comment by rajbarua** [comment]
@boeboe I was busy trying to work around this issue by setting up secondary-ip-address. I also realised that you had raised #5 on the lambda function roles. Based on that I kind of worked around the issue by
1. Using ubuntu image instead of Amazon linux
2. allocated secondary private ip address to the nodes corresponding to the  pods with multus IPs
    * basically my application is installed via ansible to the EKS cluster. After deploying my app, I queried the node names from the pods, then using AWS CLI got the instance id, and then got to the `ens6` and `ens7` interface ids, and finally added the secondary ip addresses to the interface ids. Also wrote the parts to remove this configuration when app is uninstalled. All using ansible calling kubectl and aws cli.
3. used ipvlan instead of macvlan.
    * Influenced by [this](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-ubuntu-secondary-network-interface/) guide I realised default ip routing in eks ubuntu will not support macvlan out of the box and I would have to make changes as suggested in the blog. As such I did not follow the blog but learnt enough to avoid macvlan, for now.
4. Also, I used static ip allocation for the ipvlan plugin. But others like host-local and whereabouts should also work.

Ideally I would like the secondary ip setup to be done inside the cluster so that when pods gets recreated on another node, the ip deallocation and allocation happens from within the cluster.

I will now go though https://github.com/aws-samples/eks-automated-ipmgmt-multus-pods and see if they demonstrate an easier way!

**Comment by boeboe** [comment]
Note that there was one more thing that I was doing wrong before everything worked. Since I am using self hosted ubuntu machines with self managed `kubeadm` to bootstrap my whole `multus` cluster on AWS, I had to manually enable IP FWing, which was one of the reasons traffic was not getting across.

    # Allow IP Forwarding
    echo "[Terraform Cloud Init] Allow IP Forwarding"
    sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
    sed -i 's/#net.ipv4.conf.all.rp_filter=1/net.ipv4.conf.all.rp_filter=2/g' /etc/sysctl.conf
    
    
The output of this `multus` experiment with `aws-cni` is summarized on the following Terraform module I am working on currently (WIP): https://github.com/boeboe/terraform-aws-k8s-multus-gtp5g

For some reason, this was not necessary with `calico-cni` (without `aws-cni`) so I am assuming `calico-cni` does this out of the box for you.

**Comment by raghs-aws** [comment]
Please follow the steps on the blog for the pod communication  across nodes https://github.com/aws-samples/eks-automated-ipmgmt-multus-pods
